### ISSUE TITLE
Playback rate seems to be set incorrectly

### ISSUE THREAD

**Issue by iWasntHere** [OpenPrograms/dangranos-Programs#4]
Nobody's gonna read this but I might as well report it.

Downloading a song at 32k bitrate will set playback speed at 1. The song plays incredibly fast, had to manually set playback rate to 0.675 (about as close as I can get to the original speed of the song).

Again, nobody's gonna care, but hey, what can ya do?

**Comment by SaphireLattice** [comment]
Whoa, that still works and somebody uses it? Okay, hmm... 
Oh! It seems that the base playback rate has been changed to be 48k. I'm not sure when that change was introduced into computronics though, as I haven't poked MC/OC/Computronics in forever.
By the way, try setting it to `0.666`, should be just abit better :P 

Actually, after I have written above and looked at source, you just need to pass the `-a` flag, as that is what 48k bitrate format is.

**Comment by SaphireLattice** [comment]
Fixed with latest commit, now defaults to the 48k bitrate with DFPWM 1a encoding, with option to use old encoding.
