### ISSUE TITLE
In Need of New Audio Converter

### ISSUE THREAD

**Issue by PapaBaguette** [OpenPrograms/dangranos-Programs#5]
It would appear that the Magik6 audio converter is no longer accessible. Are there any other audio converters out there that could replace it?

**Comment by SaphireLattice** [comment]
Sadly that was the only available option, unless somebody decides to host it up.

**Comment by DanyGames2014** [comment]
And cant it be hosted on github or google script or whatever is it called ?

**Comment by SaphireLattice** [comment]
If you are willing to donate some money every month, sure. Github.io is for hosting static sites though, and Google would easily be pricy when you have a public unrestricted usage service.

**Comment by DanyGames2014** [comment]
Or if you want i havr free site on hostinger and they didnt removed it and im nit using it

**Comment by SaphireLattice** [comment]
That's not quite what converter requires. Thanks for the offered help
though.

**Comment by DanyGames2014** [comment]
And what converter requires ?

**Comment by Pixel1011** [comment]
hm i could host it

**Comment by twilight-sparkle-irl** [comment]
I could host it!

**Comment by alula** [comment]
is magik6's converter source available? i could host it

**Comment by olie304** [comment]
@saphire-lattice @magik6k bump
(Can host it btw)

**Comment by magik6k** [comment]
The code is mostly built out of hacks, but here it is: https://ipfs.io/ipfs/QmcvS2wpsTMm66wG9vgchA7hkevy1vFTfw2UZ2Qwa86Jpi (requires sox, ffmpeg, youtube-dl and fcgiwrap)

**Comment by olie304** [comment]
@magik6k thx

**Comment by DanyGames2014** [comment]
@magik6k and how to use it ? And can it be hosted locally on windows ?
