### ISSUE TITLE
Server returned HTTP error 403

### ISSUE THREAD

**Issue by BILLPC2684** [OpenPrograms/dangranos-Programs#7]
so i was wanting to record a track onto a cassette tape and then this appeared
`/home # ytld https://www.youtube.com/watch?v=YIA_0cvS2gQ`
`Using tape drive [8932b55c-9dd3-4cf0-8419-c4315f82c59b]`
`Downloading YIA_0cvS2gQ`
`Total downloaded:          0 bytes`
`/usr/bin/ytdl.lua:85: Server returned HTTP response code: 403 for URL: https://dfpwm.magik6k.net/conv32/YIA_0cvS2gQ:`
`stack traceback:`
`        [C]: in function 'error'`
`        /lib/internet.lua:50: in function 'for iterator'`
`        /usr/bin/ytdl.lua:85: in function 'convertWrite'`
`        /usr/bin/ytdl.lua:108: in function </usr/bin/ytdl.lua:4>`
`        /usr/bin/ytdl.lua:4: in main chunk`
`        (...tail calls...)`
`        [C]: in function 'xpcall'`
`        machine:751: in function 'xpcall'`
`        /lib/process.lua:84: in function </lib/process.lua:80>`
`/home # `

**Comment by ghost** [comment]
same

**Comment by olie304** [comment]
It is because magik6k discontinued the online converter which means this script is completely broken. Use [one of these](https://wiki.vexatos.com/wiki:computronics:tape?s[]=recording) and [this tutorial](https://docs.google.com/document/d/1RYjLuXdsiadIHY0cfMR5UMSJbETLQZBfnQJMFrt39ss/edit) instead.

**Comment by BILLPC2684** [comment]
i've already been doing that but the quality isn't as good :|

**Comment by SaphireLattice** [comment]
Fixed by #8
